In [175]:
import DataProcess
reload(DataProcess)
from DataProcess import load_mnist
import numpy as np

In [184]:
data  = load_mnist(dataset="training", path = '../',digits = [1], selection=slice(0,4,1),zscore=False)

In [185]:
data[0].shape

(4, 785)

In [194]:
import matplotlib.pyplot as plt

images = data[0]   
image = images[1]
image = image[1:].reshape(28,28)
plt.imshow(image, cmap=plt.get_cmap('gray'))
plt.show()

In [193]:
stats.zscore(b)
print b.shape
range(0)

(2, 3)


[]

In [35]:
b[1] = np.array([[1],[2],[3]]).reshape(1,3)

In [164]:
range(3)

[0, 1, 2]

In [161]:
a = np.array([1 ,3,3])
aaa = [1,2,3,4,5]

In [163]:
np.random.shuffle(aaa)
aaa

[2, 3, 4, 1, 5]

In [243]:
a = np.array([[1,2,3],[2,3,4],[4,5,6]])
a
b = np.array([3,5,7])

for ina, inb in zip(a,b) :
    print ina, inb
a[1:,:]

[1 2 3] 3
[2 3 4] 5
[4 5 6] 7


array([[2, 3, 4],
       [4, 5, 6]])

In [223]:
a[:,1] = 0
a[:,0] = 0
a

array([[0, 0, 3],
       [0, 0, 4],
       [0, 0, 6]])

In [166]:
np.random.shuffle(a)
a

array([3, 1, 3])

In [167]:
a

array([3, 1, 3])

In [14]:
a[0] = [3,4,5]

In [15]:
a

array([[3, 4, 5],
       [2, 3, 4],
       [4, 5, 6]])

In [16]:
a[0] = np.array([1,2,3])

In [17]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [30]:
b

array([ 0.,  0.,  0.])

In [24]:
b

0.33333333333333331

In [28]:
a[0] = b

In [168]:
a

array([3, 1, 3])

In [50]:
a

array([[0, 0, 0],
       [2, 3, 4],
       [4, 5, 6]])

In [51]:
a[0] = [1,3,2]

In [52]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [53]:
meanA = a.mean(axis=0)

In [54]:
meanA

array([ 2.33333333,  3.66666667,  4.        ])

In [55]:
a - meanA

array([[-1.33333333, -0.66666667, -2.        ],
       [-0.33333333, -0.66666667,  0.        ],
       [ 1.66666667,  1.33333333,  2.        ]])

In [63]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [64]:
from scipy import stats

In [65]:
stats.zscore(a)

array([[-1.06904497, -0.70710678, -1.22474487],
       [-0.26726124, -0.70710678,  0.        ],
       [ 1.33630621,  1.41421356,  1.22474487]])

In [69]:
a[:,0] = [1,1,1]
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [70]:
stats.zscore(a)

array([[        nan, -0.70710678, -1.22474487],
       [        nan, -0.70710678,  0.        ],
       [        nan,  1.41421356,  1.22474487]])

In [78]:
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [219]:
np.insert(a, 0, 1, axis = 1)

IndexError: axis 1 is out of bounds for an array of dimension 1

In [196]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [198]:
b = [3,4]
b

[3, 4]

In [201]:
np.dot(a,b)

array([11, 25])

In [202]:
np.range(10)

AttributeError: 'module' object has no attribute 'range'

In [203]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [204]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
1*(np.array(range(10)) == 1)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [210]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [211]:
a = np.array([1,2,3,4])

In [212]:
a

array([1, 2, 3, 4])

In [213]:
[1,a]

[1, array([1, 2, 3, 4])]

In [215]:
np.insert(a, 0, 1)

array([1, 1, 2, 3, 4])

In [216]:
a = np.insert(a, 0, 1)

In [217]:
a

array([1, 1, 2, 3, 4])

In [218]:
a[0:3]

array([1, 1, 2])

In [224]:
np.exp(3)

20.085536923187668

In [225]:
a = np.array([1,3,4])
a

array([1, 3, 4])

In [228]:
np.exp(a)/np.sum(np.exp(a))

array([ 0.03511903,  0.25949646,  0.70538451])

In [229]:
np.tanh(a)

array([ 0.76159416,  0.99505475,  0.9993293 ])

In [230]:
np.multiply(tanh(a),np.tanh(a))

array([ 0.58002566,  0.99013396,  0.99865905])

In [231]:
np.multiply(tanh(a),np.tanh(a))

array([ 0.58002566,  0.99013396,  0.99865905])

In [232]:
a

array([1, 3, 4])

In [244]:
a = np.array([])

In [245]:
a

array([], dtype=float64)

In [254]:
a = np.insert(a, 7)
np.insert(a, 0,2)

TypeError: insert() takes at least 3 arguments (2 given)

In [253]:
 np.power(10.0, -1)

0.10000000000000001

In [267]:
a = np.append(a, 100)

In [271]:
a[-3:] = [88, 88, 88]
a

array([ 1,  2,  3, 88, 88, 88])

In [257]:
import matplotlib.pyplot as plt

In [274]:
a = [1, 2, 3,4]
b = [2,4,6,8]

In [259]:
b = [2,4,6,8]

In [260]:
plt(

TypeError: 'module' object is not callable

In [ ]:
plt.plot(a,b,'ro-',linewidth = 5)
plt.show()
plt.savefig('./test',ext = 'pdf')