In [82]:
import DataProcess
reload(DataProcess)
from DataProcess import load_mnist
import numpy as np

In [83]:
data  = load_mnist(dataset="training", path = '../')

In [84]:
data[0].shape

(60000, 785)

In [91]:
images = data[0]   
image = images[21]
image

array([ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.00441808, -0.00575482,
       -0.00408252, -0.00408252,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.00408252, -0.00470969,
       -0.00879935, -0.01159056, -0.01475898, -0.01928485, -0.0246718 ,
       -0.02907103, -0.03059266, -0.03116401, -0.03196287, -0.03020254,
       -0.03131022, -0.0283834 , -0.02311919, -0.01916663, -0.0167723 ,
       -0.01099636, -0.00832486, -0.00438069,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.00408252,
       -0.00539535, -0.00852241, -0.01198504, -0.01765348, -0.0277109 ,
       -0.03702009, -0.05215128, -0.0670362 , -0.08301705, -0.09

In [29]:
b = np.array([[0, 2, 3],[0, 1,4]])

In [30]:
stats.zscore(b)
print b.shape

(2, 3)


In [35]:
b[1] = np.array([[1],[2],[3]]).reshape(1,3)

In [32]:
b

array([[0, 2, 3],
       [1, 2, 3]])

In [36]:
a = np.array([1 ,3,3])

In [37]:
a.shape

(3,)

In [11]:
a = np.array([[1,2,3],[2,3,4],[4,5,6]])

In [12]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [31]:
 / 6.0
b

array([ 0.,  0.,  0.])

In [10]:
a

array([[0, 0, 0],
       [2, 3, 4],
       [4, 5, 6]])

In [14]:
a[0] = [3,4,5]

In [15]:
a

array([[3, 4, 5],
       [2, 3, 4],
       [4, 5, 6]])

In [16]:
a[0] = np.array([1,2,3])

In [17]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [30]:
b

array([ 0.,  0.,  0.])

In [24]:
b

0.33333333333333331

In [28]:
a[0] = b

In [29]:
a

array([[0, 0, 0],
       [2, 3, 4],
       [4, 5, 6]])

In [50]:
a

array([[0, 0, 0],
       [2, 3, 4],
       [4, 5, 6]])

In [51]:
a[0] = [1,3,2]

In [52]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [53]:
meanA = a.mean(axis=0)

In [54]:
meanA

array([ 2.33333333,  3.66666667,  4.        ])

In [55]:
a - meanA

array([[-1.33333333, -0.66666667, -2.        ],
       [-0.33333333, -0.66666667,  0.        ],
       [ 1.66666667,  1.33333333,  2.        ]])

In [63]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [64]:
from scipy import stats

In [65]:
stats.zscore(a)

array([[-1.06904497, -0.70710678, -1.22474487],
       [-0.26726124, -0.70710678,  0.        ],
       [ 1.33630621,  1.41421356,  1.22474487]])

In [69]:
a[:,0] = [1,1,1]
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [70]:
stats.zscore(a)

array([[        nan, -0.70710678, -1.22474487],
       [        nan, -0.70710678,  0.        ],
       [        nan,  1.41421356,  1.22474487]])

In [78]:
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [81]:
np.insert(a, 0, 1, axis = 1)

array([[1, 1, 3, 2],
       [1, 1, 3, 4],
       [1, 1, 5, 6]])